/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'race-categories': RaceCategory;
    'event-logistics': EventLogistic;
    'event-editions': EventEdition;
    media: Media;
    highlights: Highlight;
    faqs: Faq;
    sponsors: Sponsor;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'race-categories': RaceCategoriesSelect<false> | RaceCategoriesSelect<true>;
    'event-logistics': EventLogisticsSelect<false> | EventLogisticsSelect<true>;
    'event-editions': EventEditionsSelect<false> | EventEditionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    highlights: HighlightsSelect<false> | HighlightsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin panel accounts. Only Super Admins can create new accounts or change roles. Public sign-up is disabled — the only exception is Payload's own first-account setup screen when no accounts exist yet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Super Admin: full control including accounts. Editor: full content editing (settings, categories, highlights, FAQs, sponsors, navigation). Media Manager: gallery/media only.
   */
  role: 'media-manager' | 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Distances, fees and race-day times shown in the Categories section. Keep unconfirmed details marked as pending.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-categories".
 */
export interface RaceCategory {
  id: string;
  _order?: string | null;
  /**
   * Short public label, for example 5K.
   */
  name: string;
  distance: string;
  fee: string;
  reportingTime: string;
  startTime: string;
  description: string;
  ageEligibility?: string | null;
  /**
   * Only list confirmed race-kit or participant inclusions.
   */
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only active categories appear on the website.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Race-day arrival and bib expo information. Drag entries to control their public order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-logistics".
 */
export interface EventLogistic {
  id: string;
  _order?: string | null;
  title: string;
  type: 'race-day' | 'bib-expo';
  venue: string;
  address: string;
  dateTime: string;
  directions: string;
  /**
   * Optional Google Maps or other HTTP/HTTPS directions link.
   */
  mapUrl?: string | null;
  /**
   * Only active entries appear publicly.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * One reusable archive record per Agomoni Run edition. Gallery photos and official results both connect to this record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-editions".
 */
export interface EventEdition {
  id: string;
  /**
   * Public name, for example Agomoni Run 1.0.
   */
  name: string;
  /**
   * Short label such as 1.0 or 2.0.
   */
  editionLabel: string;
  /**
   * Gallery URL, for example agomoni-run-1-0.
   */
  slug: string;
  /**
   * Used to order newest and previous editions.
   */
  eventDate?: string | null;
  /**
   * Optional introduction shown above this edition's photographs.
   */
  galleryDescription?: string | null;
  /**
   * The verified external timing/results page. Leave empty while results are pending.
   */
  resultsUrl?: string | null;
  /**
   * Only enable after adding and checking the official results link.
   */
  resultsPublished: boolean;
  /**
   * Hidden editions remain editable in Studio.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload photos inactive first, then publish only images approved for the public gallery. Accessibility descriptions and visible captions are optional.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  _order?: string | null;
  /**
   * Used by screen readers and shown if the image cannot load. This text is not displayed as a caption.
   */
  altText?: string | null;
  /**
   * Displayed with the photograph in the public gallery.
   */
  caption?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Keeps logos and website artwork out of the public event gallery.
   */
  assetType: 'event-gallery' | 'site' | 'partner';
  /**
   * The archive this photograph belongs to.
   */
  galleryEdition?: (string | null) | EventEdition;
  /**
   * The photo also needs to be Live before visitors can see it.
   */
  showInGallery: boolean;
  /**
   * Controls whether visitors can see this photo publicly.
   */
  active: boolean;
  featured: boolean;
  uploadedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Confirmed event support and key race-day information shown on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlights".
 */
export interface Highlight {
  id: string;
  _order?: string | null;
  title: string;
  description: string;
  /**
   * Optional active gallery photo associated with this highlight.
   */
  photo?: (string | null) | Media;
  /**
   * Only active highlights appear publicly.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public answers shown in the homepage FAQ section. Drag rows in the list to set display order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  _order?: string | null;
  question: string;
  answer: string;
  /**
   * Only active answers appear publicly.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Publish only confirmed event and community partners. No partner is shown until its record is active.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: string;
  _order?: string | null;
  name: string;
  /**
   * Select an active image with descriptive alt text.
   */
  logo: string | Media;
  websiteUrl?: string | null;
  /**
   * Optional factual description shown beneath the partner name.
   */
  description?: string | null;
  /**
   * Only active partners appear publicly.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'race-categories';
        value: string | RaceCategory;
      } | null)
    | ({
        relationTo: 'event-logistics';
        value: string | EventLogistic;
      } | null)
    | ({
        relationTo: 'event-editions';
        value: string | EventEdition;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'highlights';
        value: string | Highlight;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: string | Sponsor;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-categories_select".
 */
export interface RaceCategoriesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  distance?: T;
  fee?: T;
  reportingTime?: T;
  startTime?: T;
  description?: T;
  ageEligibility?: T;
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-logistics_select".
 */
export interface EventLogisticsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  type?: T;
  venue?: T;
  address?: T;
  dateTime?: T;
  directions?: T;
  mapUrl?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-editions_select".
 */
export interface EventEditionsSelect<T extends boolean = true> {
  name?: T;
  editionLabel?: T;
  slug?: T;
  eventDate?: T;
  galleryDescription?: T;
  resultsUrl?: T;
  resultsPublished?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  _order?: T;
  altText?: T;
  caption?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  assetType?: T;
  galleryEdition?: T;
  showInGallery?: T;
  active?: T;
  featured?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlights_select".
 */
export interface HighlightsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  description?: T;
  photo?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  logo?: T;
  websiteUrl?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The website’s event identity, primary story, registration state, gallery introduction and contact details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  eventName: string;
  tagline: string;
  /**
   * Keep Timing confirmed off until the official flag-off time is approved.
   */
  eventDateTime: string;
  /**
   * Controls whether the website presents the time as confirmed.
   */
  timingConfirmed?: boolean | null;
  /**
   * IANA timezone used to format the event date, normally Asia/Kolkata.
   */
  timezone: string;
  venue: string;
  organiserName: string;
  organiserDescription: string;
  heroHeading: string;
  heroSubheading: string;
  /**
   * Choose an active landscape image with meaningful alt text.
   */
  heroPhoto?: (string | null) | Media;
  /**
   * Leave empty until the official registration destination is ready.
   */
  registrationUrl?: string | null;
  /**
   * Leave empty until official timing results are available.
   */
  resultsUrl?: string | null;
  /**
   * Controls the wording and state of registration information.
   */
  registrationStatus: 'soon' | 'open' | 'closed' | 'completed';
  /**
   * Show Register and Join the run actions across the website.
   */
  showRegistrationCta: boolean;
  /**
   * Show Results actions when verified results are ready.
   */
  showResultsCta: boolean;
  /**
   * The small overlay text and route-line strip layered over the hero image.
   */
  heroManifesto?: {
    bengaliWord?: string | null;
    line1?: string | null;
    line2?: string | null;
    wordmarkTop?: string | null;
    wordmarkBottom?: string | null;
    wordmarkYear?: string | null;
    routeLineStart?: string | null;
    /**
     * For example a date, distance or tagline shown after the route dot.
     */
    routeLineEnd?: string | null;
  };
  aboutBengaliWord?: string | null;
  aboutHeading?: string | null;
  /**
   * Describe the confirmed purpose of the run without unsupported claims.
   */
  about: string;
  /**
   * The first full-bleed image section, shown right after the About copy.
   */
  storyChapter?: {
    /**
     * Optional. Falls back to a stock photo when empty.
     */
    image?: (string | null) | Media;
    imageAlt?: string | null;
    word?: string | null;
    lead?: string | null;
    heading?: string | null;
  };
  /**
   * The second image section, alongside the “Join the run” call to action.
   */
  communityChapter?: {
    /**
     * Optional. Falls back to a stock photo when empty.
     */
    image?: (string | null) | Media;
    imageAlt?: string | null;
    tag?: string | null;
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
  };
  /**
   * A short notice displayed above the homepage header when enabled.
   */
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  contactEmail?: string | null;
  primaryPhone?: string | null;
  secondaryPhone?: string | null;
  instagramUrl?: string | null;
  facebookUrl?: string | null;
  youtubeUrl?: string | null;
  galleryTitle: string;
  galleryDescription: string;
  /**
   * The edition previewed on the homepage. When empty, the newest public edition with photos is used.
   */
  featuredGalleryEdition?: (string | null) | EventEdition;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header menu, mobile menu and footer links shown on every page. Drag rows to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  /**
   * Shown in the floating header on desktop and in the mobile menu.
   */
  headerLinks?:
    | {
        label: string;
        /**
         * An internal path like /#about or /gallery, or a full https:// URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in the footer's Explore column.
   */
  footerLinks?:
    | {
        label: string;
        /**
         * An internal path like /#about or /gallery, or a full https:// URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  eventName?: T;
  tagline?: T;
  eventDateTime?: T;
  timingConfirmed?: T;
  timezone?: T;
  venue?: T;
  organiserName?: T;
  organiserDescription?: T;
  heroHeading?: T;
  heroSubheading?: T;
  heroPhoto?: T;
  registrationUrl?: T;
  resultsUrl?: T;
  registrationStatus?: T;
  showRegistrationCta?: T;
  showResultsCta?: T;
  heroManifesto?:
    | T
    | {
        bengaliWord?: T;
        line1?: T;
        line2?: T;
        wordmarkTop?: T;
        wordmarkBottom?: T;
        wordmarkYear?: T;
        routeLineStart?: T;
        routeLineEnd?: T;
      };
  aboutBengaliWord?: T;
  aboutHeading?: T;
  about?: T;
  storyChapter?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        word?: T;
        lead?: T;
        heading?: T;
      };
  communityChapter?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        tag?: T;
        heading?: T;
        body?: T;
        ctaLabel?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  contactEmail?: T;
  primaryPhone?: T;
  secondaryPhone?: T;
  instagramUrl?: T;
  facebookUrl?: T;
  youtubeUrl?: T;
  galleryTitle?: T;
  galleryDescription?: T;
  featuredGalleryEdition?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}